const P = (id: number) => `/images/pexels/${id}.jpg`;

export const MARKETS_SEED = [
  { name: "Pakistan", slug: "pakistan", countryCode: "PK", flag: "🇵🇰", latitude: 33.6844, longitude: 73.0479, tagline: "High-growth residential and gated community investments.", description: "Pakistan offers one of the most compelling emerging real estate markets in South Asia, with rapid urbanisation, a young population and strong demand for master-planned gated communities in Islamabad, Lahore and Karachi.", investmentOverview: "Entry prices remain attractive relative to regional peers, while rental yields in prime Islamabad sectors and Lahore's DHA phases consistently outperform. Overseas Pakistanis benefit from dedicated investment schemes and remittance incentives.", stats: [{ label: "Avg. Rental Yield", value: "6–8%" }, { label: "Capital Growth (5y)", value: "45%+" }, { label: "Entry Price", value: "PKR 25M" }], cities: ["Islamabad", "Lahore", "Karachi"], coverImage: P(7598375), featured: true, order: 1 },
  { name: "UAE", slug: "uae", countryCode: "AE", flag: "🇦🇪", latitude: 25.2048, longitude: 55.2708, tagline: "A global hub for luxury living and high ROI opportunities.", description: "The UAE remains the benchmark for international property investment — tax-free rental income, world-class infrastructure, Golden Visa pathways and unmatched lifestyle in Dubai and Abu Dhabi.", investmentOverview: "Dubai continues to record record transaction volumes with off-plan launches from premium developers. Rental yields of 6–9% are among the highest of any global city, with no annual property tax and full foreign freehold ownership.", stats: [{ label: "Avg. Rental Yield", value: "7–9%" }, { label: "Property Tax", value: "0%" }, { label: "Golden Visa", value: "AED 2M+" }], cities: ["Dubai", "Abu Dhabi", "Ras Al Khaimah"], coverImage: P(35139028), featured: true, order: 2 },
  { name: "Saudi Arabia", slug: "saudi-arabia", countryCode: "SA", flag: "🇸🇦", latitude: 24.7136, longitude: 46.6753, tagline: "Vision 2030 giga-projects reshaping a nation.", description: "Saudi Arabia is undergoing the most ambitious urban transformation on earth. Riyadh, Jeddah and the Red Sea coast are opening to international investors with premium branded residences and new-city developments.", investmentOverview: "Foreign ownership reforms, the Premium Residency programme and trillion-dollar giga-projects create an early-mover advantage for investors positioning ahead of Expo 2030 and the 2034 World Cup.", stats: [{ label: "Population Growth", value: "2.5%/yr" }, { label: "Giga-Project Value", value: "$1T+" }, { label: "Riyadh Yield", value: "5–7%" }], cities: ["Riyadh", "Jeddah", "NEOM"], coverImage: P(38096888), featured: true, order: 3 },
  { name: "Turkey", slug: "turkey", countryCode: "TR", flag: "🇹🇷", latitude: 41.0082, longitude: 28.9784, tagline: "Where Europe meets Asia — citizenship-eligible investments.", description: "Istanbul's Bosphorus-front residences and Mediterranean coastal projects combine lifestyle appeal with citizenship-by-investment eligibility, making Turkey a favourite for global buyers.", investmentOverview: "Property purchases from $400K qualify for Turkish citizenship. Strong tourism demand supports short-let yields in Istanbul, Antalya and Bodrum, while lira-denominated pricing offers currency-driven entry points.", stats: [{ label: "Citizenship Threshold", value: "$400K" }, { label: "Tourism Arrivals", value: "50M+/yr" }, { label: "Istanbul Yield", value: "5–7%" }], cities: ["Istanbul", "Antalya", "Bodrum"], coverImage: P(35142390), featured: false, order: 4 },
  { name: "Azerbaijan", slug: "azerbaijan", countryCode: "AZ", flag: "🇦🇿", latitude: 40.4093, longitude: 49.8671, tagline: "Caspian luxury with strong capital growth.", description: "Baku's waterfront skyline is one of the region's fastest-evolving luxury markets, supported by energy wealth, tourism growth and major infrastructure investment.", investmentOverview: "Sea-view residences along Baku Boulevard and White City deliver strong appreciation with comparatively low entry prices. Residency permits are accessible for property owners.", stats: [{ label: "Avg. Rental Yield", value: "6–8%" }, { label: "Entry Price", value: "$180K" }, { label: "Residency", value: "Available" }], cities: ["Baku", "Gabala"], coverImage: P(35295995), featured: false, order: 5 },
  { name: "UK", slug: "uk", countryCode: "GB", flag: "🇬🇧", latitude: 51.5074, longitude: -0.1278, tagline: "The world's most resilient prime property market.", description: "London remains the safe-haven capital of global real estate, with prime central and regeneration-zone opportunities in Manchester and Birmingham offering strong long-term fundamentals.", investmentOverview: "Sterling-denominated assets, transparent legal title and robust rental demand from students and professionals underpin the UK market. Regional cities deliver yields of 5–7% with strong capital growth forecasts.", stats: [{ label: "London Prime Growth", value: "3–4%/yr" }, { label: "Regional Yield", value: "5–7%" }, { label: "Legal Framework", value: "Freehold / Leasehold" }], cities: ["London", "Manchester", "Birmingham"], coverImage: P(28288859), featured: true, order: 6 },
  { name: "USA", slug: "usa", countryCode: "US", flag: "🇺🇸", latitude: 25.7617, longitude: -80.1918, tagline: "Deep, liquid and dollar-denominated.", description: "From Miami's waterfront towers to Texas' booming metros, the United States offers scale, liquidity and dollar-based returns in the world's largest property market.", investmentOverview: "Florida and Texas benefit from no state income tax, strong migration and a landlord-friendly environment. Branded residences in Miami and new-build communities in Dallas and Austin lead investor demand.", stats: [{ label: "Miami Price Growth (5y)", value: "60%+" }, { label: "State Income Tax (FL/TX)", value: "0%" }, { label: "Avg. Yield", value: "5–6%" }], cities: ["Miami", "New York", "Dallas"], coverImage: P(38026454), featured: false, order: 7 },
  { name: "Spain", slug: "spain", countryCode: "ES", flag: "🇪🇸", latitude: 40.4168, longitude: -3.7038, tagline: "Mediterranean lifestyle with European stability.", description: "Spain's Costa del Sol, Costa Blanca and Madrid combine enviable climate with a mature legal framework and steady tourism-led rental demand.", investmentOverview: "Coastal villas and Madrid apartments attract European and Middle Eastern buyers seeking lifestyle plus yield. Short-term rentals in Marbella and Alicante deliver seasonal premiums.", stats: [{ label: "Tourism Arrivals", value: "85M+/yr" }, { label: "Coastal Yield", value: "4–6%" }, { label: "Price Growth (2024)", value: "8%" }], cities: ["Madrid", "Marbella", "Alicante"], coverImage: P(2771935), featured: false, order: 8 },
  { name: "France", slug: "france", countryCode: "FR", flag: "🇫🇷", latitude: 48.8566, longitude: 2.3522, tagline: "Timeless prestige in Paris and the Riviera.", description: "Paris Haussmannian apartments and Côte d'Azur villas represent the pinnacle of heritage luxury with enduring international demand.", investmentOverview: "Supply-constrained Paris arrondissements deliver consistent appreciation, while Nice and Cannes command premium seasonal rents. French property offers strong wealth preservation.", stats: [{ label: "Paris Avg. Price", value: "€10K/m²" }, { label: "Riviera Yield", value: "3–5%" }, { label: "Market Type", value: "Prime / Heritage" }], cities: ["Paris", "Nice", "Cannes"], coverImage: P(36771569), featured: false, order: 9 },
  { name: "Oman", slug: "oman", countryCode: "OM", flag: "🇴🇲", latitude: 23.588, longitude: 58.3829, tagline: "Serene coastal living with freehold residency.", description: "Oman's Integrated Tourism Complexes give foreign buyers freehold title and residency in one of the Gulf's most naturally beautiful and stable nations.", investmentOverview: "Muscat's Al Mouj and coastal ITC developments offer villas and marina residences at prices well below Dubai, with residency visas for owners and their families.", stats: [{ label: "Entry Price", value: "OMR 90K" }, { label: "Residency", value: "With purchase" }, { label: "Avg. Yield", value: "5–7%" }], cities: ["Muscat", "Salalah", "Sohar"], coverImage: P(209218), featured: false, order: 10 },
];

const amenitiesLux = ["Infinity Pool", "Private Gym", "Concierge", "Smart Home", "Covered Parking", "Kids Play Area", "24/7 Security", "Landscaped Gardens"];

export const PROJECTS_SEED = [
  { name: "The Lagoon Residences", slug: "the-lagoon-residences", market: "uae", country: "UAE", city: "Dubai", address: "Mohammed Bin Rashid City, Dubai", latitude: 25.1615, longitude: 55.3006, developer: "Meydan Group", shortDescription: "Crystal lagoon-front apartments in the heart of MBR City.", description: "The Lagoon Residences reimagines waterfront living in the centre of Dubai. Set along a 7km crystal lagoon with private beach access, each residence features floor-to-ceiling glazing, Italian kitchens and panoramic skyline views. Residents enjoy resort-style amenities including a beach club, wellness pavilion and lush landscaped promenades.", price: "2200000", currency: "AED", roi: "8.2%", propertyType: "Apartment", bedrooms: "1–3", bathrooms: "2–4", area: "780 – 2,150 sq ft", handover: "Q4 2026", status: "under-construction", featured: true, order: 1, coverImage: P(13256066), gallery: [P(33537703), P(1497417), P(35139019)], specifications: [{ label: "Payment Plan", value: "60/40" }, { label: "Service Charge", value: "AED 14/sq ft" }, { label: "Ownership", value: "Freehold" }], floorPlans: [{ name: "1 Bedroom — Type A", area: "780 sq ft" }, { name: "2 Bedroom — Type C", area: "1,320 sq ft" }, { name: "3 Bedroom — Type E", area: "2,150 sq ft" }] },
  { name: "Serene Hills Villas", slug: "serene-hills-villas", market: "pakistan", country: "Pakistan", city: "Islamabad", address: "Sector E-11, Islamabad", latitude: 33.7, longitude: 72.98, developer: "Margalla Developers", shortDescription: "Contemporary villas with Margalla Hills views.", description: "Serene Hills Villas is a gated collection of 48 architect-designed homes overlooking the Margalla Hills National Park. Each villa offers double-height living spaces, private lawns and rooftop terraces, with a private community club, mosque and jogging trails.", price: "85000000", currency: "PKR", roi: "7.5%", propertyType: "Villa", bedrooms: "4–6", bathrooms: "5–7", area: "1 – 2 Kanal", handover: "Q2 2026", status: "under-construction", featured: true, order: 2, coverImage: P(8134821), gallery: [P(7598375), P(14989324)], specifications: [{ label: "Plot Sizes", value: "1 & 2 Kanal" }, { label: "Payment Plan", value: "3 Years" }, { label: "Title", value: "CDA Approved" }] },
  { name: "Riyadh Crest Residences", slug: "riyadh-crest-residences", market: "saudi-arabia", country: "Saudi Arabia", city: "Riyadh", address: "King Abdullah Financial District, Riyadh", latitude: 24.7663, longitude: 46.6421, developer: "ROSHN", shortDescription: "Branded residences in the financial heart of Riyadh.", description: "Riyadh Crest Residences delivers hotel-standard living in KAFD — the Kingdom's new financial capital. Residences feature private lift lobbies, a sky lounge and direct connectivity to the metro network, positioned for the city's Vision 2030 growth.", price: "4300000", currency: "SAR", roi: "6.8%", propertyType: "Apartment", bedrooms: "2–4", bathrooms: "3–5", area: "140 – 320 m²", handover: "Q1 2027", status: "under-construction", featured: true, order: 3, coverImage: P(38096888), gallery: [P(35295995), P(19784888)], specifications: [{ label: "Ownership", value: "Foreign eligible" }, { label: "Payment Plan", value: "50/50" }] },
  { name: "Bosphorus Heights", slug: "bosphorus-heights", market: "turkey", country: "Turkey", city: "Istanbul", address: "Beşiktaş, Istanbul", latitude: 41.043, longitude: 29.0094, developer: "Emlak Konut", shortDescription: "Citizenship-eligible residences with Bosphorus views.", description: "Bosphorus Heights rises above Beşiktaş with uninterrupted views of the strait. The project combines Ottoman-inspired gardens with contemporary interiors and qualifies for Turkish citizenship by investment.", price: "850000", currency: "USD", roi: "6.1%", propertyType: "Apartment", bedrooms: "2–4", bathrooms: "2–3", area: "120 – 260 m²", handover: "Ready", status: "ready", featured: true, order: 4, coverImage: P(35142390), gallery: [P(35139026), P(7245349)], specifications: [{ label: "Citizenship", value: "Eligible" }, { label: "Title Deed", value: "Tapu Ready" }] },
  { name: "Azure Bay Tower", slug: "azure-bay-tower", market: "azerbaijan", country: "Azerbaijan", city: "Baku", address: "Baku White City, Baku", latitude: 40.3777, longitude: 49.8741, developer: "Pasha Construction", shortDescription: "Caspian-front residences in Baku White City.", description: "Azure Bay Tower is a 32-storey landmark on the Caspian shoreline with a residents' marina club, spa and panoramic sky garden.", price: "620000", currency: "USD", roi: "7.0%", propertyType: "Apartment", bedrooms: "1–3", bathrooms: "1–3", area: "75 – 190 m²", handover: "Q3 2026", status: "under-construction", featured: true, order: 5, coverImage: P(35295995), gallery: [P(1497417), P(19784888)] },
  { name: "Thames Quarter", slug: "thames-quarter", market: "uk", country: "United Kingdom", city: "London", address: "Nine Elms, London SW8", latitude: 51.4808, longitude: -0.1296, developer: "Berkeley Group", shortDescription: "Riverside apartments in London's newest cultural district.", description: "Thames Quarter sits in Nine Elms, London's fastest-growing riverside district, moments from the new US Embassy and Battersea Power Station. Residents enjoy a rooftop garden, 24-hour concierge and private cinema.", price: "1450000", currency: "GBP", roi: "4.5%", propertyType: "Apartment", bedrooms: "1–3", bathrooms: "1–3", area: "560 – 1,480 sq ft", handover: "Q2 2026", status: "under-construction", featured: true, order: 6, coverImage: P(28288859), gallery: [P(209218), P(18506889)], specifications: [{ label: "Tenure", value: "999-year lease" }, { label: "Zone", value: "Zone 1" }] },
  { name: "Brickell Skyline Residences", slug: "brickell-skyline-residences", market: "usa", country: "United States", city: "Miami", address: "Brickell Avenue, Miami, FL", latitude: 25.7617, longitude: -80.1918, developer: "Related Group", shortDescription: "Bay-view residences in Miami's financial district.", description: "Brickell Skyline Residences offers turnkey furnished residences with Biscayne Bay views, a resort deck and short-term rental flexibility — ideal for investors seeking dollar income.", price: "1900000", currency: "USD", roi: "5.6%", propertyType: "Apartment", bedrooms: "1–3", bathrooms: "2–3", area: "820 – 1,900 sq ft", handover: "Q4 2027", status: "under-construction", featured: false, order: 7, coverImage: P(38026454), gallery: [P(35295995), P(7245349)] },
  { name: "Costa Blanca Villas", slug: "costa-blanca-villas", market: "spain", country: "Spain", city: "Alicante", address: "Cabo Roig, Orihuela Costa, Alicante", latitude: 37.9186, longitude: -0.7314, developer: "TM Grupo Inmobiliario", shortDescription: "Modern sea-view villas on the Costa Blanca.", description: "Costa Blanca Villas is a boutique enclave of detached homes with private pools, solariums and Mediterranean views, minutes from blue-flag beaches and championship golf.", price: "795000", currency: "EUR", roi: "5.2%", propertyType: "Villa", bedrooms: "3–4", bathrooms: "3–4", area: "180 – 240 m²", handover: "Q3 2026", status: "under-construction", featured: false, order: 8, coverImage: P(2771935), gallery: [P(8134821), P(7598375)] },
  { name: "Maison Étoile", slug: "maison-etoile", market: "france", country: "France", city: "Paris", address: "16th Arrondissement, Paris", latitude: 48.8637, longitude: 2.2769, developer: "Emerige", shortDescription: "Haussmannian elegance, renovated for modern life.", description: "Maison Étoile is a meticulous restoration of a 19th-century Haussmannian building near the Arc de Triomphe, with parquet floors, mouldings and contemporary kitchens.", price: "2100000", currency: "EUR", roi: "3.8%", propertyType: "Apartment", bedrooms: "2–4", bathrooms: "2–3", area: "95 – 210 m²", handover: "Ready", status: "ready", featured: false, order: 9, coverImage: P(36771569), gallery: [P(209218), P(14989324)] },
  { name: "Al Mouj Marina Residences", slug: "al-mouj-marina-residences", market: "oman", country: "Oman", city: "Muscat", address: "Al Mouj, Muscat", latitude: 23.6258, longitude: 58.2724, developer: "Al Mouj Muscat", shortDescription: "Marina-front freehold homes with Omani residency.", description: "Al Mouj Marina Residences offers freehold apartments and townhouses overlooking a 400-berth marina, with an 18-hole golf course, beach club and residency visa for owners.", price: "285000", currency: "OMR", roi: "6.4%", propertyType: "Townhouse", bedrooms: "2–4", bathrooms: "2–4", area: "130 – 280 m²", handover: "Q1 2027", status: "coming-soon", featured: false, order: 10, coverImage: P(209218), gallery: [P(35139028), P(18506889)] },
  { name: "Palm Vista Villas", slug: "palm-vista-villas", market: "uae", country: "UAE", city: "Dubai", address: "Palm Jumeirah, Dubai", latitude: 25.1124, longitude: 55.139, developer: "Nakheel", shortDescription: "Beachfront signature villas on Palm Jumeirah.", description: "Palm Vista Villas are limited-edition beachfront homes on the fronds of Palm Jumeirah, each with private beach, pool and views of the Dubai skyline.", price: "6800000", currency: "AED", roi: "6.0%", propertyType: "Villa", bedrooms: "5–6", bathrooms: "6–7", area: "6,500 – 8,200 sq ft", handover: "Ready", status: "available", featured: false, order: 11, coverImage: P(7598375), gallery: [P(35139019), P(33537703)] },
  { name: "Marina Loft Apartments", slug: "marina-loft-apartments", market: "uae", country: "UAE", city: "Dubai", address: "Dubai Marina, Dubai", latitude: 25.0805, longitude: 55.1403, developer: "Emaar", shortDescription: "Loft-style investor apartments in Dubai Marina.", description: "Marina Loft Apartments is an investor-focused tower in Dubai Marina with high rental demand, walkable to the beach, metro and tram.", price: "1100000", currency: "AED", roi: "8.8%", propertyType: "Apartment", bedrooms: "Studio–2", bathrooms: "1–2", area: "450 – 1,150 sq ft", handover: "Q2 2026", status: "under-construction", featured: false, order: 12, coverImage: P(18506889), gallery: [P(1497417), P(19784888)] },
].map((p) => ({ amenities: amenitiesLux, specifications: [] as { label: string; value: string }[], floorPlans: [] as { name: string; area?: string; image?: string }[], documents: [{ name: "Project Brochure (PDF)", url: "#brochure" }], published: true, ...p }));

export const SECTIONS_SEED = [
  { page: "home", key: "hero", order: 1, eyebrow: "Welcome to MR.HOME", title: "Invest Wise. Live Better.", subtitle: null, body: "Curated luxury properties across 10 global markets. Your trusted partner in international real estate.", ctaLabel: "Explore Projects", ctaHref: "/projects", secondaryCtaLabel: "Explore Markets", secondaryCtaHref: "/markets", image: "/images/hero-villa.jpg", items: [] },
  { page: "home", key: "stats", order: 2, title: "Our Journey. Your Success.", items: [{ value: "10", label: "Global Markets", icon: "globe" }, { value: "200+", label: "Premium Projects", icon: "building" }, { value: "15K+", label: "Happy Clients", icon: "users" }, { value: "$2B+", label: "Value of Properties Sold", icon: "chart" }, { value: "100%", label: "Trust & Transparency", icon: "shield" }] },
  { page: "home", key: "why", order: 3, eyebrow: "Why Mr.Home", title: "Why Mr.Home", subtitle: "Because Your Future Deserves the Best", body: "We combine local expertise with global standards to bring you high-value investment opportunities.", ctaLabel: "Discover More", ctaHref: "/why-mr-home", items: [{ title: "Prime Locations", description: "Handpicked locations with high growth potential.", icon: "map-pin" }, { title: "High ROI", description: "Strong returns backed by market intelligence.", icon: "trending-up" }, { title: "Trusted Partner", description: "Transparent deals and end-to-end support.", icon: "handshake" }, { title: "Premium Quality", description: "World-class projects with unmatched value.", icon: "shield-check" }] },
  { page: "home", key: "earth", order: 4, eyebrow: "Global Presence", title: "Global Presence, Local Expertise", body: "We operate in 10 dynamic markets worldwide, bringing the best investment opportunities closer to you.", ctaLabel: "Explore All Markets", ctaHref: "/markets", items: [] },
  { page: "home", key: "projects", order: 5, eyebrow: "Portfolio", title: "Premium Projects Across The Globe", body: "A curated selection of developments from the world's most trusted developers.", ctaLabel: "View All Projects", ctaHref: "/projects", items: [] },
  { page: "home", key: "journey", order: 6, eyebrow: "Track Record", title: "Our Journey. Your Success.", body: "From first consultation to handover, our advisors guide every step of your international investment.", image: P(7245349), items: [{ title: "Consultation", description: "Understand your goals, budget and preferred markets." }, { title: "Curation", description: "Shortlist vetted projects matched to your strategy." }, { title: "Acquisition", description: "Secure the unit with transparent developer terms." }, { title: "Aftercare", description: "Handover, leasing and portfolio management support." }] },
  { page: "home", key: "inquiry", order: 7, eyebrow: "Contact", title: "Let’s Find the Right Property for You", body: "Share your requirements and our experts will get in touch with you.", image: P(7245349), items: [] },
  { page: "why-mr-home", key: "hero", order: 1, eyebrow: "Why Mr.Home", title: "Why Mr.Home", body: "A boutique international advisory with the reach of a global network. We exist to make cross-border property investment clear, secure and rewarding.", image: P(35139019), items: [] },
  { page: "why-mr-home", key: "values", order: 2, title: "What Sets Us Apart", items: [{ title: "Global Expertise", description: "Advisors on the ground in 10 markets across four continents.", icon: "globe" }, { title: "Investment Intelligence", description: "Data-led market research behind every recommendation.", icon: "trending-up" }, { title: "Premium Developments", description: "Direct partnerships with tier-one developers only.", icon: "building" }, { title: "Local Market Knowledge", description: "Regulatory, legal and cultural insight in every jurisdiction.", icon: "map-pin" }, { title: "Client-First Advisory", description: "No pressure. Independent advice aligned to your goals.", icon: "handshake" }, { title: "Trusted Opportunities", description: "Every project is vetted for title, escrow and delivery record.", icon: "shield-check" }] },
  { page: "why-mr-home", key: "process", order: 3, title: "How We Work", items: [{ title: "01 — Discovery", description: "A confidential consultation to define your objectives." }, { title: "02 — Strategy", description: "A tailored market and project shortlist with projected returns." }, { title: "03 — Acquisition", description: "Negotiation, due diligence and secure transaction management." }, { title: "04 — Beyond", description: "Leasing, resale and portfolio growth advisory." }] },
  { page: "contact", key: "hero", order: 1, eyebrow: "Contact", title: "Let’s Find the Right Property for You", body: "Speak with an advisor about any of our 10 markets. We respond within one business day.", items: [] },
  { page: "projects", key: "hero", order: 1, eyebrow: "Portfolio", title: "Premium Projects Across The Globe", body: "Browse curated developments across our 10 markets. Filter by market, property type and status.", items: [] },
  { page: "markets", key: "hero", order: 1, eyebrow: "Markets", title: "Global Presence, Local Expertise", body: "Ten carefully selected markets, each chosen for growth, stability and lifestyle.", items: [] },
];

export const NAV_SEED = [
  { location: "header", label: "Home", href: "/", order: 1 },
  { location: "header", label: "Why Mr.Home", href: "/why-mr-home", order: 2 },
  { location: "header", label: "Projects", href: "/projects", order: 3 },
  { location: "header", label: "Markets", href: "/markets", order: 4 },
  { location: "header", label: "Contact", href: "/contact", order: 5 },
  { location: "footer", label: "Home", href: "/", order: 1 },
  { location: "footer", label: "Why Mr.Home", href: "/why-mr-home", order: 2 },
  { location: "footer", label: "Projects", href: "/projects", order: 3 },
  { location: "footer", label: "Markets", href: "/markets", order: 4 },
  { location: "footer", label: "Contact", href: "/contact", order: 5 },
];

export const LEGAL_SEED = [
  { slug: "privacy-policy", title: "Privacy Policy", content: `# Privacy Policy\n\nMR.HOME respects your privacy. This policy explains what personal data we collect, why we collect it and how we protect it.\n\n## Information We Collect\n\n- Contact details you submit through our inquiry forms (name, email, phone, WhatsApp).\n- Investment preferences such as market, budget and property interest.\n- Technical data such as IP address, browser and pages visited, used for security and analytics.\n\n## How We Use Your Data\n\n- To respond to your inquiries and connect you with an advisor.\n- To send project updates you have requested.\n- To protect our platform against abuse and fraud.\n\n## Your Rights\n\nYou may request access, correction or deletion of your personal data at any time by contacting us using the details on our Contact page.\n\n## Data Retention\n\nLead data is retained for as long as necessary to provide our services or as required by law.` },
  { slug: "terms", title: "Terms & Conditions", content: `# Terms & Conditions\n\nBy using the MR.HOME website you agree to these terms.\n\n## Nature of Service\n\nMR.HOME is a real estate marketing and advisory company. We market properties on behalf of third-party developers and do not act as the developer or seller.\n\n## Investment Disclaimer\n\nAll prices, payment plans, ROI figures, rental yields and handover dates are indicative, provided by developers and subject to change without notice. Past performance is not a guarantee of future returns. You should obtain independent legal and financial advice before any purchase.\n\n## Intellectual Property\n\nAll content, branding and imagery on this website is owned by MR.HOME or licensed from its partners and may not be reproduced without permission.\n\n## Limitation of Liability\n\nTo the fullest extent permitted by law, MR.HOME shall not be liable for any loss arising from reliance on information published on this website.` },
  { slug: "cookie-policy", title: "Cookie Policy", content: `# Cookie Policy\n\nThis website uses cookies to deliver a secure, fast experience.\n\n## Essential Cookies\n\nRequired for security, session management and form protection. These cannot be disabled.\n\n## Analytics Cookies\n\nUsed only with your consent to understand how visitors use the site so we can improve it. You can withdraw consent at any time by clearing your browser cookies and declining on the consent banner.\n\n## Managing Cookies\n\nMost browsers allow you to block or delete cookies through their settings. Blocking essential cookies may affect site functionality.` },
];

export const FAQ_SEED = [
  { question: "Can foreigners buy property in the UAE?", answer: "Yes. Non-residents can purchase freehold property in designated areas of Dubai and Abu Dhabi with full ownership rights.", order: 1 },
  { question: "Do you charge buyers a commission?", answer: "In most markets our fees are paid by the developer, meaning our advisory service is free to buyers. We disclose any exceptions upfront.", order: 2 },
  { question: "Which markets offer residency with property purchase?", answer: "The UAE (Golden Visa), Turkey (citizenship), Oman, Azerbaijan and Spain offer residency pathways linked to qualifying property investment.", order: 3 },
  { question: "How do I get started?", answer: "Submit an inquiry or message us on WhatsApp. An advisor will schedule a consultation to understand your goals and shortlist suitable projects.", order: 4 },
];

export const TESTIMONIAL_SEED = [
  { name: "Ahmed R.", role: "Investor, Riyadh", quote: "MR.HOME guided my first Dubai purchase end-to-end. Transparent, responsive and genuinely independent advice.", order: 1 },
  { name: "Sarah M.", role: "Overseas Pakistani, London", quote: "Investing back home felt risky until MR.HOME handled the due diligence. The Islamabad villa is now rented and appreciating.", order: 2 },
  { name: "Elena K.", role: "Family Office, Baku", quote: "Their market intelligence across the Gulf and Europe is exceptional. A partner we trust with multi-market allocations.", order: 3 },
];

export const WHATSAPP_TEMPLATES_SEED = [
  { key: "default", name: "General Inquiry", template: "Hello MR.HOME, I would like to learn more about your property opportunities." },
  { key: "project", name: "Project Inquiry", template: "Hello MR.HOME, I'm interested in {{project}} in {{market}}. Please share more details." },
  { key: "market", name: "Market Inquiry", template: "Hello MR.HOME, I'm interested in investment opportunities in {{market}}." },
];

export const SEO_SEED = [
  { path: "/", title: "MR.HOME — Invest Wise. Live Better.", description: "Curated luxury properties across 10 global markets. Your trusted partner in international real estate." },
  { path: "/projects", title: "Premium Projects Across The Globe | MR.HOME", description: "Browse curated luxury developments across the UAE, Saudi Arabia, UK, USA, Turkey, Pakistan and more." },
  { path: "/markets", title: "Global Presence, Local Expertise | MR.HOME", description: "Explore investment opportunities in 10 carefully selected international real estate markets." },
  { path: "/why-mr-home", title: "Why Mr.Home | MR.HOME", description: "Global expertise, investment intelligence and client-first advisory for international property investors." },
  { path: "/contact", title: "Contact MR.HOME | Let’s Find the Right Property for You", description: "Speak with an international real estate advisor about any of our 10 markets." },
];

export const CITIES_SEED = [
  // UAE
  { market: "uae", name: "Dubai", slug: "dubai", latitude: 25.2048, longitude: 55.2708, tagline: "The world's luxury property capital.", description: "Dubai combines record-breaking skylines with tax-free yields, Golden Visa eligibility and full foreign freehold ownership across its prime districts.", stats: [{ label: "Avg. Yield", value: "6–9%" }, { label: "Price Growth (5y)", value: "60%+" }, { label: "Entry Price", value: "AED 1M" }], featured: true, order: 1 },
  { market: "uae", name: "Abu Dhabi", slug: "abu-dhabi", latitude: 24.4539, longitude: 54.3773, tagline: "Capital calm, sovereign-grade stability.", description: "Abu Dhabi offers lower-density luxury, Saadiyat cultural landmarks and long-term sovereign backing for patient investors.", stats: [{ label: "Avg. Yield", value: "5–7%" }, { label: "Entry Price", value: "AED 1.2M" }], featured: false, order: 2 },
  { market: "uae", name: "Ras Al Khaimah", slug: "ras-al-khaimah", latitude: 25.7895, longitude: 55.9432, tagline: "Beachfront value north of Dubai.", description: "RAK delivers the UAE lifestyle at the emirate's friendliest entry prices, with growing tourism demand along Al Marjan Island.", stats: [{ label: "Avg. Yield", value: "7–8%" }, { label: "Entry Price", value: "AED 550K" }], featured: false, order: 3 },
  // Pakistan
  { market: "pakistan", name: "Islamabad", slug: "islamabad", latitude: 33.6844, longitude: 73.0479, tagline: "Gated communities beneath the Margallas.", description: "Islamabad's CDA-approved sectors and DHA phases offer the country's most stable premium residential market with strong overseas demand.", stats: [{ label: "Avg. Yield", value: "6–8%" }, { label: "Entry Price", value: "PKR 25M" }], featured: true, order: 1 },
  { market: "pakistan", name: "Lahore", slug: "lahore", latitude: 31.5204, longitude: 74.3587, tagline: "Pakistan's cultural and commercial engine.", description: "Lahore's DHA phases and new mega-societies deliver the deepest transaction volumes and consistent capital growth.", stats: [{ label: "Avg. Yield", value: "5–7%" }, { label: "Entry Price", value: "PKR 18M" }], featured: false, order: 2 },
  { market: "pakistan", name: "Karachi", slug: "karachi", latitude: 24.8607, longitude: 67.0011, tagline: "The coastal financial megacity.", description: "Karachi's Clifton and DHA waterfront remain the country's highest-density investment corridors with resilient rental demand.", stats: [{ label: "Avg. Yield", value: "5–6%" }, { label: "Entry Price", value: "PKR 15M" }], featured: false, order: 3 },
  // Saudi Arabia
  { market: "saudi-arabia", name: "Riyadh", slug: "riyadh", latitude: 24.7136, longitude: 46.6753, tagline: "Vision 2030's beating heart.", description: "Riyadh's KAFD, ROSHN and Diriyah giga-projects anchor the Kingdom's transformation into a global business capital.", stats: [{ label: "Avg. Yield", value: "5–7%" }, { label: "Growth (2024)", value: "11%" }], featured: true, order: 1 },
  { market: "saudi-arabia", name: "Jeddah", slug: "jeddah", latitude: 21.4858, longitude: 39.1925, tagline: "Gateway to the Red Sea.", description: "Jeddah's waterfront corniche and new downtown position it as the Red Sea's tourism and logistics hub.", stats: [{ label: "Avg. Yield", value: "5–6%" }, { label: "Tourism", value: "Rising" }], featured: false, order: 2 },
  // Turkey
  { market: "turkey", name: "Istanbul", slug: "istanbul", latitude: 41.0082, longitude: 28.9784, tagline: "Two continents, one skyline.", description: "Istanbul's Bosphorus and new-financial-district residences combine citizenship eligibility with a deep domestic market.", stats: [{ label: "Citizenship", value: "$400K" }, { label: "Avg. Yield", value: "5–7%" }], featured: true, order: 1 },
  { market: "turkey", name: "Antalya", slug: "antalya", latitude: 36.8969, longitude: 30.7133, tagline: "Mediterranean resort living.", description: "Antalya's coastal villas deliver strong short-let yields driven by year-round tourism demand.", stats: [{ label: "Short-let Yield", value: "6–8%" }], featured: false, order: 2 },
  // Azerbaijan
  { market: "azerbaijan", name: "Baku", slug: "baku", latitude: 40.4093, longitude: 49.8671, tagline: "Caspian waterfront momentum.", description: "Baku Boulevard towers and White City residences offer Europe's lowest entry prices for seafront luxury.", stats: [{ label: "Avg. Yield", value: "6–8%" }, { label: "Entry Price", value: "$180K" }], featured: true, order: 1 },
  // UK
  { market: "uk", name: "London", slug: "london", latitude: 51.5074, longitude: -0.1278, tagline: "The world's safe-haven asset.", description: "Prime central London remains the benchmark for wealth preservation with transparent freehold title.", stats: [{ label: "Prime Growth", value: "3–4%/yr" }, { label: "Avg. Price", value: "£10K/sq ft" }], featured: true, order: 1 },
  { market: "uk", name: "Manchester", slug: "manchester", latitude: 53.4808, longitude: -2.2426, tagline: "The North's investment engine.", description: "Manchester's regeneration zones deliver the UK's strongest regional rental yields and student demand.", stats: [{ label: "Avg. Yield", value: "6–7%" }], featured: false, order: 2 },
  { market: "uk", name: "Birmingham", slug: "birmingham", latitude: 52.4862, longitude: -1.8904, tagline: "HS2's biggest winner.", description: "Birmingham's city-centre regeneration and HS2 connectivity underpin long-term capital growth.", stats: [{ label: "Avg. Yield", value: "5–7%" }], featured: false, order: 3 },
  // USA
  { market: "usa", name: "Miami", slug: "miami", latitude: 25.7617, longitude: -80.1918, tagline: "Dollar income, zero state tax.", description: "Miami's branded residences and waterfront towers attract global wealth migration and short-let premiums.", stats: [{ label: "Growth (5y)", value: "60%+" }, { label: "State Tax", value: "0%" }], featured: true, order: 1 },
  { market: "usa", name: "New York", slug: "new-york", latitude: 40.7128, longitude: -74.006, tagline: "The ultimate global city.", description: "Manhattan condominiums remain the deepest, most liquid luxury market in the Americas.", stats: [{ label: "Avg. Yield", value: "3–4%" }], featured: false, order: 2 },
  { market: "usa", name: "Dallas", slug: "dallas", latitude: 32.7767, longitude: -96.797, tagline: "Corporate relocation boomtown.", description: "Dallas builds for the corporate migration wave with landlord-friendly, high-yield new communities.", stats: [{ label: "Avg. Yield", value: "6–7%" }], featured: false, order: 3 },
  // Spain
  { market: "spain", name: "Madrid", slug: "madrid", latitude: 40.4168, longitude: -3.7038, tagline: "Europe's sunniest capital market.", description: "Madrid's prime barrios combine supply constraints with steady European institutional demand.", stats: [{ label: "Growth (2024)", value: "8%" }], featured: true, order: 1 },
  { market: "spain", name: "Marbella", slug: "marbella", latitude: 36.5101, longitude: -4.8856, tagline: "Costa del Sol's golden mile.", description: "Marbella villas command Europe's most resilient seasonal rental premiums.", stats: [{ label: "Short-let Yield", value: "5–7%" }], featured: false, order: 2 },
  { market: "spain", name: "Alicante", slug: "alicante", latitude: 38.3452, longitude: -0.4811, tagline: "Blue-flag beaches, villa value.", description: "Alicante's Costa Blanca offers the Mediterranean's friendliest entry prices for lifestyle buyers.", stats: [{ label: "Avg. Yield", value: "4–6%" }], featured: false, order: 3 },
  // France
  { market: "france", name: "Paris", slug: "paris", latitude: 48.8566, longitude: 2.3522, tagline: "Heritage wealth preservation.", description: "Haussmannian freeholds in central arrondissements are Europe's most supply-constrained luxury stock.", stats: [{ label: "Avg. Price", value: "€10K/m²" }], featured: true, order: 1 },
  { market: "france", name: "Nice", slug: "nice", latitude: 43.7102, longitude: 7.262, tagline: "The Riviera's capital.", description: "Nice balances year-round living with strong Côte d'Azur seasonal rents.", stats: [{ label: "Avg. Yield", value: "3–5%" }], featured: false, order: 2 },
  { market: "france", name: "Cannes", slug: "cannes", latitude: 43.5528, longitude: 7.0174, tagline: "Festival-season premiums.", description: "Cannes delivers the Riviera's highest weekly rates during congress and festival season.", stats: [{ label: "Peak Yield", value: "6%+" }], featured: false, order: 3 },
  // Oman
  { market: "oman", name: "Muscat", slug: "muscat", latitude: 23.588, longitude: 58.3829, tagline: "Freehold serenity on the Gulf of Oman.", description: "Muscat's Integrated Tourism Complexes grant freehold title and residency at prices well below Dubai.", stats: [{ label: "Entry Price", value: "OMR 90K" }, { label: "Residency", value: "With purchase" }], featured: true, order: 1 },
  { market: "oman", name: "Salalah", slug: "salalah", latitude: 17.0151, longitude: 54.0924, tagline: "The Khareef coast.", description: "Salalah's monsoon coast is an emerging resort market with growing GCC tourism.", stats: [{ label: "Avg. Yield", value: "5–6%" }], featured: false, order: 2 },
];
